version: '3.8'

services:
  dash:
    build:
      context: .
      dockerfile: Dockerfile
    image: sreedocker123/ddaas:encryptlatest 
    container_name: ddaas
    ports:
      - "8050:8050"  # Change port if necessary
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: Msois@123
      MYSQL_USER: sois
      MYSQL_PASSWORD: Msois@123

  mysql:
    #build:
    #context: ./database_38 
    #dockerfile: Dockerfile
    image: mysql:latest  
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Msois@123
      MYSQL_USER: sois
      MYSQL_PASSWORD: Msois@123
    ports:
      - "3308:3306"  # Change port if necessary
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database_38/updated_database_38.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
        #- ./database_38/my.cnf:/etc/mysql/my.cnf  # Mount custom MySQL configuration file
        #command: --innodb_use_native_aio=0  # Use this command to ensure compatibility with certain file systems
      #command: ['--innodb_read_only_compressed=OFF']

volumes:
  mysql_data:

